
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'commandAS CALL COMMA CREATE DISCARD DO END EQ EXPORT FROM GE GT ID IMPORT JOIN LE LIMIT LT NEQ NUMBER PRINT PROCEDURE RENAME SELECT SEMI STAR STRING TABLE USING WHEREcommand : SELECT column_list FROM ID where_opt limit_opt SEMIcolumn_list : STARcolumn_list : ID COMMA column_listcolumn_list : IDwhere_opt : WHERE conditionwhere_opt : limit_opt : LIMIT NUMBERlimit_opt : condition : ID EQ value\n                 | ID GT value\n                 | ID LT valuevalue : NUMBER\n             | STRINGcommand : IMPORT TABLE ID FROM STRING SEMIcommand : EXPORT TABLE ID AS STRING SEMIcommand : CREATE TABLE ID FROM ID JOIN ID USING ID SEMIcommand : DISCARD TABLE ID SEMIcommand : RENAME TABLE ID ID SEMIcommand : PRINT TABLE ID SEMI'
    
_lr_action_items = {'SELECT':([0,],[2,]),'IMPORT':([0,],[3,]),'EXPORT':([0,],[4,]),'CREATE':([0,],[5,]),'DISCARD':([0,],[6,]),'RENAME':([0,],[7,]),'PRINT':([0,],[8,]),'$end':([1,31,33,39,44,45,47,60,],[0,-17,-19,-18,-14,-15,-1,-16,]),'STAR':([2,19,],[11,11,]),'ID':([2,12,13,14,15,16,17,18,19,24,30,35,46,58,],[10,20,21,22,23,24,25,26,10,32,38,43,52,59,]),'TABLE':([3,4,5,6,7,8,],[12,13,14,15,16,17,]),'FROM':([9,10,11,20,22,27,],[18,-4,-2,28,30,-3,]),'COMMA':([10,],[19,]),'AS':([21,],[29,]),'SEMI':([23,25,26,32,34,36,37,40,42,48,53,54,55,56,57,59,],[31,33,-6,39,-8,44,45,47,-5,-7,-9,-12,-13,-10,-11,60,]),'WHERE':([26,],[35,]),'LIMIT':([26,34,42,53,54,55,56,57,],[-6,41,-5,-9,-12,-13,-10,-11,]),'STRING':([28,29,49,50,51,],[36,37,55,55,55,]),'JOIN':([38,],[46,]),'NUMBER':([41,49,50,51,],[48,54,54,54,]),'EQ':([43,],[49,]),'GT':([43,],[50,]),'LT':([43,],[51,]),'USING':([52,],[58,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'column_list':([2,19,],[9,27,]),'where_opt':([26,],[34,]),'limit_opt':([34,],[40,]),'condition':([35,],[42,]),'value':([49,50,51,],[53,56,57,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> SELECT column_list FROM ID where_opt limit_opt SEMI','command',7,'p_command_select','parser.py',8),
  ('column_list -> STAR','column_list',1,'p_column_list_all','parser.py',12),
  ('column_list -> ID COMMA column_list','column_list',3,'p_column_list','parser.py',16),
  ('column_list -> ID','column_list',1,'p_column_list_one','parser.py',20),
  ('where_opt -> WHERE condition','where_opt',2,'p_where_opt','parser.py',24),
  ('where_opt -> <empty>','where_opt',0,'p_where_opt_empty','parser.py',28),
  ('limit_opt -> LIMIT NUMBER','limit_opt',2,'p_limit_opt','parser.py',32),
  ('limit_opt -> <empty>','limit_opt',0,'p_limit_opt_empty','parser.py',36),
  ('condition -> ID EQ value','condition',3,'p_condition','parser.py',40),
  ('condition -> ID GT value','condition',3,'p_condition','parser.py',41),
  ('condition -> ID LT value','condition',3,'p_condition','parser.py',42),
  ('value -> NUMBER','value',1,'p_value','parser.py',46),
  ('value -> STRING','value',1,'p_value','parser.py',47),
  ('command -> IMPORT TABLE ID FROM STRING SEMI','command',6,'p_command_import','parser.py',54),
  ('command -> EXPORT TABLE ID AS STRING SEMI','command',6,'p_command_export','parser.py',58),
  ('command -> CREATE TABLE ID FROM ID JOIN ID USING ID SEMI','command',10,'p_command_create','parser.py',62),
  ('command -> DISCARD TABLE ID SEMI','command',4,'p_command_discard','parser.py',66),
  ('command -> RENAME TABLE ID ID SEMI','command',5,'p_command_rename','parser.py',70),
  ('command -> PRINT TABLE ID SEMI','command',4,'p_command_print','parser.py',74),
]
